---

- name: Combine file lists
  set_fact:
    copy_files_list_combined: '{{
      (copy_files_list       | d([]) | list) +
      (copy_files_group_list | d([]) | list) +
      (copy_files_host_list  | d([]) | list) }}'

## Could use the file module, but this would require getting the dirname first.
- name: Ensure that parent directories exist
  shell: mkdir --parents $(dirname "{{ item.dest }}")
  changed_when: False
  when: (
          item is mapping and (
            (item.create_parent_dirs is defined and item.create_parent_dirs) or
            item.create_parent_dirs is undefined or
            not item.create_parent_dirs
          )
        )
  with_items: '{{ copy_files_list_combined }}'

- name: Copy files to target system
  copy:
    dest:           '{{ item.dest }}'
    backup:         '{{ item.backup         | default(omit) }}'
    content:        '{{ item.content        | default(omit) }}'
    directory_mode: '{{ item.directory_mode | default(omit) }}'
    follow:         '{{ item.follow         | default(omit) }}'
    force:          '{{ item.force          | default(omit) }}'
    group:          '{{ item.group          | default(omit) }}'
    mode:           '{{ item.mode           | default(omit) }}'
    owner:          '{{ item.owner          | default(omit) }}'
    selevel:        '{{ item.selevel        | default(omit) }}'
    serole:         '{{ item.serole         | default(omit) }}'
    setype:         '{{ item.setype         | default(omit) }}'
    seuser:         '{{ item.seuser         | default(omit) }}'
    src:            '{{ item.src            | default(omit) }}'
    validate:       '{{ item.validate       | default(omit) }}'
  # ignore_errors: copy_ignore_errors
  # ignore_errors: yes
  # failed_when: True
  ## Not working, see: https://github.com/ansible/ansible/issues/3107
  when: (
          item is mapping and (
            item.state is string and item.state == 'present' or
            item.state is undefined
          )
        )
  with_items: '{{ copy_files_list_combined }}'

- name: Delete files if state is absent
  file:
    path: '{{ item.dest }}'
    state: 'absent'
  when: (item.state is string and item.state == 'absent')
  with_items: '{{ copy_files_list_combined }}'
